bind_addr = ":8080"
log_level = "debug"
requestfreq = 500
sendmessagetimeout = 2500
[storage]
    host = "localhost"
    port = "5432"
    database = "BASE1"
    username = "postgres"
    password = "12345"
    attempts2con = 5
[nats]
    serverID = "test-cluster"
    clientID = "client-123"
    natsUrl = "nats://nats-streaming:4222"
    interval = 1
    maxout = 5